# Generated by Django 6.1 on 2026-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='contact@itrtv.bj', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.CharField(blank=True, default='Cotonou, Bénin', max_length=200)),
                ('footer_description', models.TextField(blank=True, default="Média numérique béninois dédié à l'information en continu : articles, direct, reportages et interviews.")),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=100092600381179')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/itr_tv/')),
                ('youtube_url', models.URLField(blank=True, default='https://www.youtube.com/@InfosenTempsR%C3%A9elTV')),
                ('whatsapp_url', models.URLField(blank=True, default='https://whatsapp.com/channel/0029VaJlAKUDp2Q7oIN36632')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/feed/')),
                ('tiktok_url', models.URLField(blank=True, default='https://www.tiktok.com/@infosentempsreel?lang=fr')),
                ('x_url', models.URLField(blank=True, default='https://x.com/itr_tv')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
