# Generated by Django 6.1 on 2026-10-07 14:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attached_pdf',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='articles/pdfs/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='articles/covers/'),
        ),
    ]
