# Generated by Django 6.1 on 2026-08-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('home_top', 'Accueil - Haut'), ('home_sidebar', 'Accueil - Latéral'), ('article_inline', 'Article - Intégré'), ('webtv_preroll', 'Web TV - Pré-roll')], max_length=30)),
                ('image', models.URLField()),
                ('target_url', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('impressions_count', models.PositiveIntegerField(default=0)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='ads.sponsor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
