# Generated by Django 6.1 on 2026-08-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbanner',
            options={'ordering': ['-created_at']},
        ),
    ]
